# Generated by Django 4.2.1 on 2024-07-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uveď název kategorie pro transakce (např. potraviny, doprava, zábava)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailnější popis kategorie pro transakce (volitelný)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='CZK', help_text='Preferovaná měna uživatele', max_length=5)),
                ('user', models.OneToOneField(on_delete=models.SET('deleted_user'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Uveď částku transakce v [CZK]', max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Datum provedení transakce')),
                ('person', models.CharField(choices=[('kuba', 'Kuba'), ('romca', 'Romca')], help_text='Kdo transakci prováděl?', max_length=10)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', help_text='Je tato transakce výdaj nebo příjem?', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Detailnější popis transakce (volitelný)', null=True)),
                ('category', models.ForeignKey(help_text='Vyber kategorii pro tuto transakci', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetlog.category')),
            ],
        ),
    ]
