# Generated by Django 5.1.1 on 2025-11-23 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uveďte jméno knihy', max_length=100, verbose_name='Jméno knihy')),
                ('description', models.TextField(blank=True, help_text='Popis knihy (volitelný)', null=True, verbose_name='Popis knihy')),
                ('owner', models.ForeignKey(help_text='Majitel knihy', on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Majitel')),
            ],
            options={
                'verbose_name': 'Kniha',
                'verbose_name_plural': 'Knihy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uveď název kategorie pro transakce (např. potraviny, doprava, zábava)', max_length=200, verbose_name='Název')),
                ('color', models.CharField(default='#000000', help_text='Barva kategorie pro zobrazení v grafu ročního přehledu', max_length=7, verbose_name='Barva kategorie')),
                ('description', models.TextField(blank=True, help_text='Detailnější popis kategorie pro transakce (volitelný)', null=True, verbose_name='Popis')),
                ('is_default', models.BooleanField(default=False)),
                ('book', models.ForeignKey(help_text='Vyberte knihu, ke které patří tato kategorie', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budgetlog.book', verbose_name='Kniha')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uveď název tagu.', max_length=25, verbose_name='Název tagu')),
                ('color', models.CharField(default='#000000', help_text='Barva tagu.', max_length=7, verbose_name='Barva tagu')),
                ('description', models.TextField(blank=True, help_text='Popis tagu (volitelný).', null=True, verbose_name='Popis tagu')),
                ('book', models.ForeignKey(help_text='Vyberte knihu, ke které patří tento tag', on_delete=django.db.models.deletion.CASCADE, to='budgetlog.book', verbose_name='Kniha')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagy',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Uveďte částku transakce v [CZK].', max_digits=10, verbose_name='Částka')),
                ('datestamp', models.DateField(default=django.utils.timezone.now, help_text='Datum provedení transakce.', verbose_name='Datum')),
                ('description', models.TextField(blank=True, help_text='Zadejte detailnější popis transakce (volitelný).', null=True, verbose_name='Popis')),
                ('type', models.CharField(choices=[('income', 'Příjem'), ('expense', 'Výdaj')], default='expense', help_text='Zvolte, zda je tato transakce výdaj nebo příjem.', max_length=7, verbose_name='Typ')),
                ('book', models.ForeignKey(help_text='Vyberte knihu, ke které patří tato transakce', on_delete=django.db.models.deletion.CASCADE, to='budgetlog.book', verbose_name='Kniha')),
                ('category', models.ForeignKey(help_text='Vyberte kategorii pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetlog.category', verbose_name='Kategorie')),
                ('tags', models.ManyToManyField(blank=True, help_text='Vyberte tagy pro tuto transakci.', related_name='transactions', to='budgetlog.tag', verbose_name='Tagy')),
            ],
            options={
                'verbose_name': 'Transakce',
                'verbose_name_plural': 'Transakce',
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_book_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'book'), name='unique_category_name_book'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'book'), name='unique_tag_name_book'),
        ),
    ]
