# Generated by Django 4.2.1 on 2024-07-20 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now, help_text='Datum provedení transakce'),
        ),
    ]
