# Generated by Django 4.2.1 on 2024-07-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0002_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='datestamp',
        ),
    ]
