# Generated by Django 4.2.1 on 2024-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0004_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Uveď název kategorie pro transakce (např. potraviny, doprava, zábava)', max_length=200, unique=True, verbose_name='Název'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
