# Generated by Django 4.2.1 on 2024-07-21 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0005_alter_category_name_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Uveď částku transakce v [CZK].', max_digits=10, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Vyber kategorii pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetlog.category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datestamp',
            field=models.DateField(default=django.utils.timezone.now, help_text='Datum provedení transakce.', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Detailnější popis transakce (volitelný).', null=True, verbose_name='Popis'),
        ),
    ]
