# Generated by Django 5.0.7 on 2024-08-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0006_alter_transaction_amount_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Vyber kategorii pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgetlog.category', verbose_name='Kategorie'),
        ),
    ]
