# Generated by Django 5.0.7 on 2024-08-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0008_alter_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uveď jméno či označení účtu', max_length=100, unique=True, verbose_name='Jméno účtu')),
                ('description', models.TextField(blank=True, help_text='Detailnější popis účtu (volitelný)', null=True, verbose_name='Popis účtu')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Vyber kategorii pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgetlog.category', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(help_text='Vyber účet pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgetlog.account', verbose_name='Účet'),
        ),
    ]
