# Generated by Django 5.0.7 on 2024-08-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0009_account_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='person',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Vyber kategorii pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetlog.category', verbose_name='Kategorie'),
        ),
    ]
