# Generated by Django 5.0.7 on 2024-08-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0011_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(help_text='Vyberte účet pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgetlog.account', verbose_name='Účet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Uveďte částku transakce v [CZK].', max_digits=10, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Vyberte kategorii pro tuto transakci.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetlog.category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Zadejte detailnější popis transakce (volitelný).', null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Příjem'), ('expense', 'Výdaj')], default='expense', help_text='Zvolte, zda je tato transakce výdaj nebo příjem?', max_length=7, verbose_name='Typ'),
        ),
    ]
