# Generated by Django 5.0.7 on 2024-08-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0013_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
