# Generated by Django 5.0.7 on 2024-08-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0014_rename_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vyplň název databáze transakcí', max_length=255, verbose_name='Název databáze transakcí')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Databáze transakcí',
                'verbose_name_plural': 'Databáze transakcí',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlog.project'),
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlog.project'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlog.project'),
        ),
    ]
