# Generated by Django 5.1.1 on 2024-09-19 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0015_book_account_book_category_book_transaction_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(help_text='Majitel knihy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Majitel'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='Uveďte jméno knihy', max_length=100, unique=True, verbose_name='Jméno knihy'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'owner')},
        ),
    ]
