# Generated by Django 5.1.1 on 2024-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlog', '0019_alter_account_book_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
